services:
  # MongoDB Service
  db:
    image: mongo
    restart: always
    volumes:
      - mongodb-data:/data/db
  
  # App Service
  app:
    image: gatreh/uppgift3
    restart: always
    ports:
      - 80:8080
    environment:
      - MongoDbSettings__ConnectionString=mongodb://db:27017
      - TODO_SERVICE_IMPLEMENTATION=MongoDb
      - ASPNETCORE_ENVIRONMENT=Development

# Volumes
volumes:
  mongodb-data:
